version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Long@1234
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql_data:/var/opt/mssql

  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ShortUrl;User Id=sa;Password=Long@1234;TrustServerCertificate=True;Trusted_Connection=False;MultipleActiveResultSets=True;"
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

volumes:
  sql_data:
